### PR TITLE
Docs: Mention "time" being set in minutes [semver:patch]

### PR DESCRIPTION
**Pull request by olleolleolle**
### Motivation, issues

Some of the code mentions the `time` parameter being in minutes, but not all.

### Description

Mention "minutes" in the description of the "time" parameter.

### CODE REVIEW

**Review by eddiewebb — APPROVED** [review]
Thanks!

**Comment by eddiewebb** [comment]
Bors merge

**Comment by eddiewebb** [comment]
BotComment: *Development* version of orb available for manual validation - `eddiewebb/queue@dev:54`

**Comment by eddiewebb** [comment]
BotComment: *Production* version of orb available for use - `eddiewebb/queue@1.4.2`

**Comment by olleolleolle** [comment]
Agh, dang it, I saw that there was a second `time` parameter in the manual (which also needs this documentation note).

**Pull request merged**
