### PR TITLE
[semver:patch] docs: Mention minutes in parameter.time in until_front_of_line Command

### PR DESCRIPTION
**Pull request by olleolleolle**
This PR does what #54 did, but for the other Command.

### Motivation, issues

Completeness of documentation.

### Description

Use same wording as #54 to make it easy to grasp the parameter.

### CODE REVIEW

**Comment by eddiewebb** [comment]
bors +

**Comment by olleolleolle** [comment]
Could it, uh, retry? @eddiewebb ?

**Comment by eddiewebb** [comment]
hey sorry @olleolleolle , SSH went bad on circleci causing builds to fail. thats fixed and tests are running again (and therefore should merge shortly, sorry again, and thanks for your contribution)
https://github.com/eddiewebb/circleci-queue/runs/2824911333

**Comment by eddiewebb** [comment]
bors r+
(or so help me....)

**Pull request merged**
