### PR TITLE
pass vcs-type param to job

### PR DESCRIPTION
**Pull request by alonisser**
Currently job does not accept the vcs-type parameter nor pass it to the step
This PR is supposed to fix that

Nice Orb, kudos

### CODE REVIEW

**Comment by alonisser** [comment]
@eddiewebb I think the test failure has nothing to do with the PR but with missing token configured on PR push, any way I can actually run the tests?

**Review by eddiewebb — APPROVED** [review]

**Comment by eddiewebb** [comment]
Thank you! Build failed because no credentials, change is fine.

**Comment by alonisser** [comment]
Thanks @eddiewebb for this great Orb, when can we expect to be able to use the new code on my circleci project?

**Comment by eddiewebb** [comment]
Already live, hooray for CI (CD)!
https://circleci.com/gh/eddiewebb/circleci-queue/129?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

looks like 1.1.1 is the latest.

**Comment by alonisser** [comment]
Thanks @eddiewebb !
But this looks like a PR merged 26 days ago. and now I see this PR has not been merged (approved and closed) :(

**Comment by eddiewebb** [comment]
Sorry about that.. merged now. Assuming this workflow passes you can see the new version from the last job.
https://circleci.com/workflow-run/c2060b87-8224-41df-890f-5792a79beb30

**Comment by alonisser** [comment]
Thanks! great

**Pull request merged**
