### PR TITLE
support `tag-pattern` wrapped with slashes [semver:patch]

### PR DESCRIPTION
**Pull request by duniul**
### Checklist

- [x] All new jobs, commands, executors, parameters have descriptions
- [ ] Examples have been added for any significant new features
- [ ] README has been updated, if necessary

### Motivation, issues

**Issue**
Patterns passed to CircleCI's own tag/branch filters (e.g. [`filters.tags.only`](https://circleci.com/docs/2.0/configuration-reference/#tags)) are required to be wrapped with `/` to indicate that they are patterns, like `/^release-.*/`. However, if you pass the same pattern as `tag-pattern` to `until_front_of_line` it gets stuck in an infinite queue because it passes the slashes as part of the pattern.

**Motivation**
- Stripping wrapping slashes allows reusing the same pattern aliases for both a job filter and a queue step:
```yml
aliases:
  - &tag_pattern /^example-.*/
  
jobs:
  queue_job:
    steps:
      - queue/until_front_of_line:
          tag-pattern: *tag_pattern

workflows:
  version: 2

  example_workflow:
    jobs:
      - queue_job:
          filters:
            tags:
              only: *tag_pattern
```
- As a CircleCI orb, it makes sense to support syntax that is similar to that of CircleCI 
- Git tags/refs are not allowed to begin or end with a slash, so this change should not affect any existing patterns and be fully backward-compatible ([see item 6 here](https://git-scm.com/docs/git-check-ref-format)).

### Description

 
 - Remove wrapping slashes from the `tag-pattern` parameter
  
 I'm not sure how to write a test for this as I'm not really familiar with BATS or orb testing. 🙏

### CODE REVIEW

**Comment by eddiewebb** [comment]
bors try

@duniul - I'll work on a test, but will have bors publish a dev version you can try out as well.

**Comment by eddiewebb** [comment]
BotComment: *Development* version of orb available for manual validation - `eddiewebb/queue@dev:74`

**Comment by duniul** [comment]
@eddiewebb Testing the orb I noticed a related issue: if the current build doesn't match the provided tag pattern (either because it's incorrect or because its own tag doesn't match the pattern) it gets filtered out of the list of active builds. This means `augmented_jobstatus.json` ends up empty and `oldest_commit_time` is `null`, getting the queue infinitely stuck.

I've fixed this in 9b965e7 by excluding the current build from the tag filtering step 👍  would you mind creating another dev version build and I'll try it out?

**Comment by eddiewebb** [comment]
bors try

**Comment by eddiewebb** [comment]
BotComment: *Development* version of orb available for manual validation - `eddiewebb/queue@dev:74`

**Comment by duniul** [comment]
@eddiewebb Thanks! We've been using this in several workflow runs today and it seems to work correctly now 🎉

**Comment by eddiewebb** [comment]
bors merge

**Comment by eddiewebb** [comment]
BotComment: *Development* version of orb available for manual validation - `eddiewebb/queue@dev:74`

**Comment by eddiewebb** [comment]
bors merge

**Comment by eddiewebb** [comment]
BotComment: *Development* version of orb available for manual validation - `eddiewebb/queue@dev:74`

**Comment by eddiewebb** [comment]
BotComment: *Production* version of orb available for use - `eddiewebb/queue@1.6.4`

**Comment by calvin-cdev** [comment]
just caught up on this. nice contribution @duniul :D

**Comment by calvin-cdev** [comment]
wanted to note that this broke our usage of tag-pattern
we had ours set to the following:
```
# jq regex uses `\\` for escape characters
tag-pattern: 'v0\\.\\d+\\.\\d+$'
```

which produced the following error when running after updating to use the orb with this PR's changes:
```
jq: error: Invalid escape at line 1, column 6 (while parsing '"\.\d"') at <top-level>, line 1:
[ .[] | select((.build_num | . == "85161") or (.vcs_tag | (. != null and ****("v0\.\d+\.\d+$"))) ) ]                                                                                 
jq: error: Invalid escape at line 1, column 6 (while parsing '"\.\d"') at <top-level>, line 1:
[ .[] | select((.build_num | . == "85161") or (.vcs_tag | (. != null and ****("v0\.\d+\.\d+$"))) ) ]                                                                                      
jq: 2 compile errors

Exited with code exit status 3

```

**Comment by eddiewebb** [comment]
@calvin-summer shoot sorry. Not clear though, Do we need to tweak this further, or is it easy fix in config once known?

**Comment by calvin-cdev** [comment]
> @calvin-summer shoot sorry. Not clear though, Do we need to tweak this further, or is it easy fix in config once known?

going to work on it after the weekend. I'll update in this thread when I've figured it out.

**Pull request merged**
