### PR TITLE
feat: add issue and pull request template, based on the ones from CircleCI

### PR DESCRIPTION
**Pull request by chrishelgert**
This MR introduces issue und pull-request templates with the same format as the ones from https://github.com/CircleCI-Public/circleci-orbs/tree/staging/.github.

This increases the UX for CircleCI orbs across the different projects :)

### CODE REVIEW

**Review by KyleTryon — CHANGES_REQUESTED** [review]
Hello Chris,

Would you mind migrating this to the new issue template folder recommended by github's new template procedures?

https://help.github.com/en/articles/manually-creating-a-single-issue-template-for-your-repository#adding-an-issue-template

**Comment by chrishelgert** [comment]
Hi Kyle,

i updated the PR to the new issue template structure, so the default template is now a bug template, if you have ideas for other issue templates a can add it :)

**Comment by eddiewebb** [comment]
bors try

**Comment by KyleTryon** [comment]
Appears `PULL_REQUEST_TEMPLATE.md ` still needs to be migrated.

**Comment by eddiewebb** [comment]
bors try

**Comment by chrishelgert** [comment]
Hi Kyle,
i made a demo for the pull request template, because there is no such surface as for the issue templates.
If you want to have multiple pull request templates it looks like you have to specify them in the URL:

**Default:**
* https://github.com/chrishelgert/demo-multiple-pullrequest-templates/compare/test?expand=1

**Manually adding the template to the URL**
* https://github.com/chrishelgert/demo-multiple-pullrequest-templates/compare/test?expand=1&template=demo1.md

Are you sure you want to migrate the pull request templates to this format?
In my opinion it would be better to stay with the current pull request template format and stitch to multiple templates if there is also in the UI the possiblity to choose between the templates.

If you want it that way, i will change it :)

**Comment by eddiewebb** [comment]
bors merge

**Comment by eddiewebb** [comment]
BotComment: *Development* version of orb available for manual validation - `eddiewebb/queue@dev:32`

**Pull request merged**
